-- 开演台（角色开演台）功能表结构
-- 同时兼容 H2（本地开发，MODE=PostgreSQL）与 PostgreSQL（容器部署）

-- 剧本
CREATE TABLE IF NOT EXISTS scripts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  genre VARCHAR(60),
  difficulty VARCHAR(20),
  duration_minutes INT NOT NULL,
  player_count INT NOT NULL,
  summary VARCHAR(500)
);

-- 剧本角色（每个角色有性别要求：MALE/FEMALE/ANY）
CREATE TABLE IF NOT EXISTS script_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  script_id BIGINT NOT NULL,
  name VARCHAR(80) NOT NULL,
  gender_requirement VARCHAR(10) NOT NULL,
  description VARCHAR(500),
  position_no INT NOT NULL
);

-- 主持人（DM）
CREATE TABLE IF NOT EXISTS hosts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  title VARCHAR(80),
  phone VARCHAR(30)
);

-- 玩家（会员/到场玩家池）
CREATE TABLE IF NOT EXISTS players (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  gender VARCHAR(10) NOT NULL,
  phone VARCHAR(30)
);

-- 开演场次（开演台）
-- status: STAGING（待开演/入座中） CONFIRMED（已确认，角色定版） CANCELLED（已取消）
CREATE TABLE IF NOT EXISTS stage_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  script_id BIGINT NOT NULL,
  host_id BIGINT NOT NULL,
  session_date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  start_at TIMESTAMP NOT NULL,
  end_at TIMESTAMP NOT NULL,
  cleanup_minutes INT NOT NULL DEFAULT 20,
  status VARCHAR(12) NOT NULL DEFAULT 'STAGING',
  confirmed_at TIMESTAMP,
  note VARCHAR(300),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 场次报名名单（候选池，可超过角色数，多余者为候补）
CREATE TABLE IF NOT EXISTS session_roster (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL,
  player_id BIGINT NOT NULL,
  joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (session_id, player_id)
);

-- 角色分座版本（抽签/重抽/确认都会生成不可变版本）
-- kind: DRAW（抽签/重抽） CONFIRM（确认定版） MANUAL（手动调整）
CREATE TABLE IF NOT EXISTS assignment_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL,
  version_no INT NOT NULL,
  kind VARCHAR(10) NOT NULL,
  change_note VARCHAR(500),
  created_by VARCHAR(80),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 角色分座版本明细：每个角色一位玩家
CREATE TABLE IF NOT EXISTS assignment_version_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id BIGINT NOT NULL,
  session_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  player_id BIGINT
);

-- 换角申请（确认后任何换角走店长确认）
-- status: PENDING（待店长确认） APPROVED（已批准，角色已定版更新） REJECTED（已驳回）
CREATE TABLE IF NOT EXISTS role_swap_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  from_player_id BIGINT,
  to_player_id BIGINT NOT NULL,
  reason VARCHAR(300),
  status VARCHAR(10) NOT NULL DEFAULT 'PENDING',
  review_note VARCHAR(300),
  created_by VARCHAR(80),
  reviewed_by VARCHAR(80),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed_at TIMESTAMP
);
